# Generated by Django 5.2 on 2025-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_gadget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget_table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
